// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAy5a6fnmOyWxdEqNhuGBRO0u49fUgcZoc',
    appId: '1:764513514761:web:d94804ec8a16e19dbe8fd8',
    messagingSenderId: '764513514761',
    projectId: 'semuny-62126',
    authDomain: 'semuny-62126.firebaseapp.com',
    storageBucket: 'semuny-62126.appspot.com',
    measurementId: 'G-NGG0ERCWBC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC17ZJZ8GDGSAUSmQV5wqXTFy_KTtRXM1Q',
    appId: '1:764513514761:android:e9eb473ff6ec9826be8fd8',
    messagingSenderId: '764513514761',
    projectId: 'semuny-62126',
    storageBucket: 'semuny-62126.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBbxDx3cST1QVayBXvPtqX15rPtKEUY1eQ',
    appId: '1:764513514761:ios:c79fc1812b70ce93be8fd8',
    messagingSenderId: '764513514761',
    projectId: 'semuny-62126',
    storageBucket: 'semuny-62126.appspot.com',
    iosBundleId: 'com.example.semuny',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBbxDx3cST1QVayBXvPtqX15rPtKEUY1eQ',
    appId: '1:764513514761:ios:2cc9a19b98263b95be8fd8',
    messagingSenderId: '764513514761',
    projectId: 'semuny-62126',
    storageBucket: 'semuny-62126.appspot.com',
    iosBundleId: 'com.example.semuny.RunnerTests',
  );
}
